services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

  eureka-server:
    image: my-task-project/eureka-server:latest
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - task-network

  api-gateway:
    image: my-task-project/api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - task-network

  user-service:
    image: my-task-project/user-service:latest
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - task-network

  task-service:
    image: my-task-project/task-service:latest
    build:
      context: ./task-service
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - task-network

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge